version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=154507045281.dkr.ecr.ap-south-1.amazonaws.com/kuchbi
      - DOCKER_LOGIN_PASSWORD=$(aws ecr get-login-password  --region ap-south-1)
      - docker login -u AWS -p $DOCKER_LOGIN_PASSWORD 154507045281.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  $REPOSITORY_URI:kuchbi-${CODEBUILD_BUILD_NUMBER} .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:kuchbi-${CODEBUILD_BUILD_NUMBER}
      - echo writing image definitions file...
      - printf '[{"name":"kuchbi","imageUri":"%s"}]' $REPOSITORY_URI:kuchbi-${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
       - cat imagedefinitions.json 
      - pwd
 artifacts:
     files: imagedefinitions.json
